class OptionMenu(ctk.CTkOptionMenu):
#     def __init__(self,
#                  master: Image.Any,
#                  width: int = 140,
#                  height: int = 28,
#                  corner_radius: int | None = None,
#                  bg_color: str | Tuple[str, str] = "transparent",
#                  fg_color: str | Tuple[str, str] | None = None,
#                  button_color: str | Tuple[str, str] | None = None,
#                  button_hover_color: str | Tuple[str, str] | None = None,
#                  text_color: str | Tuple[str, str] | None = None,
#                  text_color_disabled: str | Tuple[str, str] | None = None,
#                  dropdown_fg_color: str | Tuple[str, str] | None = None, 
#                  dropdown_hover_color: str | Tuple[str, str] | None = None,
#                  dropdown_text_color: str | Tuple[str, str] | None = None,
#                  font: tuple | CTkFont | None = None, dropdown_font: tuple | CTkFont | None = None,
#                  values: list | None = None, variable: Variable | None = None, 
                 
#                  hover: bool = True, 
#                  command: Callable[[str], Any] | None = None, 
#                  dynamic_resizing: bool = True, anchor: str = "w",
#                  **kwargs):
#         super().__init__(master,
#                          width,
#                          height,
#                          corner_radius,
#                          bg_color, 
#                          fg_color, 
#                          button_color,
#                          button_hover_color, 
#                          text_color, 
#                          text_color_disabled, 
#                          dropdown_fg_color,
#                          dropdown_hover_color,
#                          dropdown_text_color,
#                          font, 
#                          dropdown_font, 
#                          values, 
#                          variable, 
#                          state,
#                          hover, 
#                          command,
#                          dynamic_resizing,
#                          anchor, 
#                          **kwargs)